src/Entity/Roteiro.php
<?php

namespace App\Entity;

use App\Repository\RoteiroRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RoteiroRepository::class)]
#[ORM\Table(name: 'roteiros')]
class Roteiro
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id_roteiro')]
    private ?int $id = null;

    #[ORM\Column]
    #[ORM\OneToOne(targetEntity: Usuario::class)]
    #[ORM\JoinColumn(name: 'id_usuario', referencedColumnName: 'id', nullable: false)]
    private ?int $id_usuario = null;

    #[ORM\Column]
    #[ORM\OneToOne(targetEntity: Destino::class)]
    #[ORM\JoinColumn(name: 'id_destino', referencedColumnName: 'id', nullable: false)]
    private ?int $id_destino = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $data_criacao = null;

    #[ORM\Column(length: 255)]
    private ?string $descricao = null;

    #[ORM\Column]
    private array $dias = [];

    public function __construct() {}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUsuario(): ?int
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(int $id_usuario): static
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    public function getIdDestino(): ?int
    {
        return $this->id_destino;
    }

    public function setIdDestino(int $id_destino): static
    {
        $this->id_destino = $id_destino;

        return $this;
    }

    public function getDataCriacao(): ?\DateTimeImmutable
    {
        return $this->data_criacao;
    }

    public function setDataCriacao(\DateTimeImmutable $data_criacao): static
    {
        $this->data_criacao = $data_criacao;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(string $descricao): static
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getDias(): array
    {
        return $this->dias;
    }

    public function setDias(array $dias): static
    {
        $this->dias = $dias;

        return $this;
    }
}

src/Form/RoteiroType.php
<?php

namespace App\Form;

use App\Entity\Roteiro;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoteiroType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_usuario')
            ->add('id_destino')
            ->add('data_criacao', null, [
                'widget' => 'single_text',
            ])
            ->add('descricao')
            ->add('dias')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Roteiro::class,
        ]);
    }
}

src/Controller/RoteiroController.php
<?php

namespace App\Controller;

use App\Entity\Roteiro;
use App\Form\RoteiroType;
use App\Repository\RoteiroRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/roteiro')]
final class RoteiroController extends AbstractController
{
    #[Route(name: 'app_roteiro_index', methods: ['GET'])]
    public function index(RoteiroRepository $roteiroRepository): Response
    {
        return $this->render('roteiro/index.html.twig', [
            'roteiros' => $roteiroRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_roteiro_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $roteiro = new Roteiro();
        $form = $this->createForm(RoteiroType::class, $roteiro);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($roteiro);
            $entityManager->flush();

            return $this->redirectToRoute('app_roteiro_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('roteiro/new.html.twig', [
            'roteiro' => $roteiro,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_roteiro_show', methods: ['GET'])]
    public function show(Roteiro $roteiro): Response
    {
        return $this->render('roteiro/show.html.twig', [
            'roteiro' => $roteiro,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_roteiro_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Roteiro $roteiro, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RoteiroType::class, $roteiro);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_roteiro_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('roteiro/edit.html.twig', [
            'roteiro' => $roteiro,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_roteiro_delete', methods: ['DELETE'])]
    public function delete(Request $request, Roteiro $roteiro, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $roteiro->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($roteiro);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_roteiro_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/roteiro/_delete_form.html.twig
<form method="post" action="{{ path('app_roteiro_delete', {'id': roteiro.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ roteiro.id) }}">
    <button class="btn">Delete</button>
</form>

templates/roteiro/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/roteiro/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Roteiro{% endblock %}

{% block body %}
    <h1>Edit Roteiro</h1>

    {{ include('roteiro/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_roteiro_index') }}">back to list</a>

    {{ include('roteiro/_delete_form.html.twig') }}
{% endblock %}

templates/roteiro/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Roteiro index{% endblock %}

{% block body %}
    <h1>Roteiro index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_usuario</th>
                <th>Id_destino</th>
                <th>Data_criacao</th>
                <th>Descricao</th>
                <th>Dias</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for roteiro in roteiros %}
            <tr>
                <td>{{ roteiro.id }}</td>
                <td>{{ roteiro.idUsuario }}</td>
                <td>{{ roteiro.idDestino }}</td>
                <td>{{ roteiro.dataCriacao ? roteiro.dataCriacao|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ roteiro.descricao }}</td>
                <td>{{ roteiro.dias ? roteiro.dias|json_encode : '' }}</td>
                <td>
                    <a href="{{ path('app_roteiro_show', {'id': roteiro.id}) }}">show</a>
                    <a href="{{ path('app_roteiro_edit', {'id': roteiro.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_roteiro_new') }}">Create new</a>
{% endblock %}

templates/roteiro/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Roteiro{% endblock %}

{% block body %}
    <h1>Create new Roteiro</h1>

    {{ include('roteiro/_form.html.twig') }}

    <a href="{{ path('app_roteiro_index') }}">back to list</a>
{% endblock %}

templates/roteiro/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Roteiro{% endblock %}

{% block body %}
    <h1>Roteiro</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ roteiro.id }}</td>
            </tr>
            <tr>
                <th>Id_usuario</th>
                <td>{{ roteiro.idUsuario }}</td>
            </tr>
            <tr>
                <th>Id_destino</th>
                <td>{{ roteiro.idDestino }}</td>
            </tr>
            <tr>
                <th>Data_criacao</th>
                <td>{{ roteiro.dataCriacao ? roteiro.dataCriacao|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Descricao</th>
                <td>{{ roteiro.descricao }}</td>
            </tr>
            <tr>
                <th>Dias</th>
                <td>{{ roteiro.dias ? roteiro.dias|json_encode : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_roteiro_index') }}">back to list</a>

    <a href="{{ path('app_roteiro_edit', {'id': roteiro.id}) }}">edit</a>

    {{ include('roteiro/_delete_form.html.twig') }}
{% endblock %}