src/Entity/Perfil.php
<?php

namespace App\Entity;

use App\Repository\PerfilRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PerfilRepository::class)]
#[ORM\Table(name: 'perfis')]
class Perfil
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id_perfil')]
    private ?int $id = null;

    #[ORM\Column]
    #[ORM\OneToOne(targetEntity: Usuario::class)]
    #[ORM\JoinColumn(name: 'id_usuario', referencedColumnName: 'id', nullable: false)]
    private ?int $id_usuario = null;

    #[ORM\Column]
    private ?int $interesse_aventura = null;

    #[ORM\Column]
    private ?int $interesse_cultura = null;

    #[ORM\Column]
    private ?int $interesse_gastronomia = null;

    #[ORM\Column]
    private ?float $orcamento_diario = null;

    #[ORM\Column]
    private ?int $duracao_viagem = null;

    #[ORM\Column(length: 255)]
    private ?string $outros_interesses = null;

    public function __construct() {}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUsuario(): ?int
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(int $id_usuario): static
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    public function getInteresseAventura(): ?int
    {
        return $this->interesse_aventura;
    }

    public function setInteresseAventura(int $interesse_aventura): static
    {
        $this->interesse_aventura = $interesse_aventura;

        return $this;
    }

    public function getInteresseCultura(): ?int
    {
        return $this->interesse_cultura;
    }

    public function setInteresseCultura(int $interesse_cultura): static
    {
        $this->interesse_cultura = $interesse_cultura;

        return $this;
    }

    public function getInteresseGastronomia(): ?int
    {
        return $this->interesse_gastronomia;
    }

    public function setInteresseGastronomia(int $interesse_gastronomia): static
    {
        $this->interesse_gastronomia = $interesse_gastronomia;

        return $this;
    }

    public function getOrcamentoDiario(): ?float
    {
        return $this->orcamento_diario;
    }

    public function setOrcamentoDiario(float $orcamento_diario): static
    {
        $this->orcamento_diario = $orcamento_diario;

        return $this;
    }

    public function getDuracaoViagem(): ?int
    {
        return $this->duracao_viagem;
    }

    public function setDuracaoViagem(int $duracao_viagem): static
    {
        $this->duracao_viagem = $duracao_viagem;

        return $this;
    }

    public function getOutrosInteresses(): ?string
    {
        return $this->outros_interesses;
    }

    public function setOutrosInteresses(string $outros_interesses): static
    {
        $this->outros_interesses = $outros_interesses;

        return $this;
    }
}

src/Form/PerfilType.php
<?php

namespace App\Form;

use App\Entity\Perfil;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PerfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_usuario')
            ->add('interesse_aventura')
            ->add('interesse_cultura')
            ->add('interesse_gastronomia')
            ->add('orcamento_diario')
            ->add('duracao_viagem')
            ->add('outros_interesses')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Perfil::class,
        ]);
    }
}

src/Controller/PerfilController.php
<?php

namespace App\Controller;

use App\Entity\Perfil;
use App\Form\PerfilType;
use App\Repository\PerfilRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/perfil')]
final class PerfilController extends AbstractController
{
    #[Route(name: 'app_perfil_index', methods: ['GET'])]
    public function index(PerfilRepository $perfilRepository): Response
    {
        return $this->render('perfil/index.html.twig', [
            'perfils' => $perfilRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_perfil_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $perfil = new Perfil();
        $form = $this->createForm(PerfilType::class, $perfil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($perfil);
            $entityManager->flush();

            return $this->redirectToRoute('app_perfil_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('perfil/new.html.twig', [
            'perfil' => $perfil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_perfil_show', methods: ['GET'])]
    public function show(Perfil $perfil): Response
    {
        return $this->render('perfil/show.html.twig', [
            'perfil' => $perfil,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_perfil_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Perfil $perfil, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PerfilType::class, $perfil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_perfil_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('perfil/edit.html.twig', [
            'perfil' => $perfil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_perfil_delete', methods: ['POST'])]
    public function delete(Request $request, Perfil $perfil, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $perfil->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($perfil);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_perfil_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/perfil/_delete_form.html.twig
<form method="post" action="{{ path('app_perfil_delete', {'id': perfil.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ perfil.id) }}">
    <button class="btn">Delete</button>
</form>

templates/perfil/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/perfil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Perfil{% endblock %}

{% block body %}
    <h1>Edit Perfil</h1>

    {{ include('perfil/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_perfil_index') }}">back to list</a>

    {{ include('perfil/_delete_form.html.twig') }}
{% endblock %}

templates/perfil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Perfil index{% endblock %}

{% block body %}
    <h1>Perfil index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_usuario</th>
                <th>Interesse_aventura</th>
                <th>Interesse_cultura</th>
                <th>Interesse_gastronomia</th>
                <th>Orcamento_diario</th>
                <th>Duracao_viagem</th>
                <th>Outros_interesses</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for perfil in perfils %}
            <tr>
                <td>{{ perfil.id }}</td>
                <td>{{ perfil.idUsuario }}</td>
                <td>{{ perfil.interesseAventura }}</td>
                <td>{{ perfil.interesseCultura }}</td>
                <td>{{ perfil.interesseGastronomia }}</td>
                <td>{{ perfil.orcamentoDiario }}</td>
                <td>{{ perfil.duracaoViagem }}</td>
                <td>{{ perfil.outrosInteresses }}</td>
                <td>
                    <a href="{{ path('app_perfil_show', {'id': perfil.id}) }}">show</a>
                    <a href="{{ path('app_perfil_edit', {'id': perfil.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_perfil_new') }}">Create new</a>
{% endblock %}

templates/perfil/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Perfil{% endblock %}

{% block body %}
    <h1>Create new Perfil</h1>

    {{ include('perfil/_form.html.twig') }}

    <a href="{{ path('app_perfil_index') }}">back to list</a>
{% endblock %}

templates/perfil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Perfil{% endblock %}

{% block body %}
    <h1>Perfil</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ perfil.id }}</td>
            </tr>
            <tr>
                <th>Id_usuario</th>
                <td>{{ perfil.idUsuario }}</td>
            </tr>
            <tr>
                <th>Interesse_aventura</th>
                <td>{{ perfil.interesseAventura }}</td>
            </tr>
            <tr>
                <th>Interesse_cultura</th>
                <td>{{ perfil.interesseCultura }}</td>
            </tr>
            <tr>
                <th>Interesse_gastronomia</th>
                <td>{{ perfil.interesseGastronomia }}</td>
            </tr>
            <tr>
                <th>Orcamento_diario</th>
                <td>{{ perfil.orcamentoDiario }}</td>
            </tr>
            <tr>
                <th>Duracao_viagem</th>
                <td>{{ perfil.duracaoViagem }}</td>
            </tr>
            <tr>
                <th>Outros_interesses</th>
                <td>{{ perfil.outrosInteresses }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_perfil_index') }}">back to list</a>

    <a href="{{ path('app_perfil_edit', {'id': perfil.id}) }}">edit</a>

    {{ include('perfil/_delete_form.html.twig') }}
{% endblock %}